# Baseline Infrastructure Configuration
---
baseline:
  namespace: "tas-monitoring"
  instance_name: "securesign-sample"
  
# TODO: OIDC Configuration Analysis Required
# - Evaluate impact of different OIDC providers on resource utilization
oidc:
  client_id: "trusted-artifact-signer"
  type: "email"

path_to_k8s_configs: "{{ playbook_dir }}"

certificates:
  organization_name: "Red Hat"
  organization_email: "jdoe@redhat.com"
  
  fulcio:
    common_name: "fulcio.hostname"
    
  tsa:
    common_name: "tsa.hostname"

storage:
  tuf_size: "100Mi"
  trillian_database_size: "10Gi"

resources:
  trillian_logserver:
    requests:
      cpu: "750m"
      memory: "768Mi"
    limits:
      cpu: "4000m"
      memory: "1.5Gi"
  trillian_logsigner:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1500m"
      memory: "1Gi"
  trillian_database:
    requests:
      cpu: "2000m"
      memory: "1Gi"
    limits:
      cpu: "4000m"
      memory: "2Gi"
  rekor:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1500m"
      memory: "1Gi"
  fulcio:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1500m"
      memory: "1Gi"
  ctlog:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  tsa:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

components:
  fulcio:
    monitoring_enabled: true
    external_access: true
    description: "Certificate Authority - issues signing certificates"
    
  rekor:
    monitoring_enabled: true
    external_access: true
    search_ui_enabled: true
    backfill_enabled: true
    description: "Transparency Log - records all signatures"
    
  trillian:
    monitoring_enabled: true
    database_create: true
    description: "Backend Database - stores transparency log data"
    
  ctlog:
    monitoring_enabled: true
    description: "Certificate Transparency Log"
    
  tsa:
    monitoring_enabled: true
    ntp_monitoring_enabled: true
    external_access: true
    description: "Timestamp Authority - provides cryptographic timestamps"
    
  tuf:
    external_access: true
    description: "The Update Framework - distributes public keys"

operators:
  rhtas:
    name: "rhtas-operator"
    namespace: "openshift-operators"
    channel: "stable"
    source: "rhtas-operator"
    sourceNamespace: "openshift-marketplace"
    
  grafana:
    name: "grafana-operator"
    namespace: "openshift-operators" 
    channel: "v5"
    source: "community-operators"
    sourceNamespace: "openshift-marketplace"

monitoring:
  enabled: true
  grafana:
    instance_name: "tas-grafana"
    admin_user: "admin"
    admin_password: "admin"
    route_name: "tas-grafana-route"
    service_account: "grafana-reader"
    token_duration: "720h"
  
  datasource:
    name: "tas-prometheus"
    prometheus_url: "https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
    time_interval: "5s"
    
  dashboard:
    name: "tas-performance-kpis"
    title: "TAS Performance Dashboard - KPIs"
    refresh_interval: "10s"
    time_range: "15m"