# Main Baseline Infrastructure Playbook
---
- name: "Deploy TAS Baseline Infrastructure"
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars_files:
    - baseline-config.yml
    
  vars:
    baseline_namespace: "{{ baseline.namespace }}"
    
  pre_tasks:
    - name: "Display deployment overview"
      debug:
        msg:
          - "TAS Baseline Infrastructure Deployment"
          - "Target namespace: {{ baseline_namespace }}"
          - "OIDC provider: {{ oidc.issuer_url }}"
          - "Components: fulcio, rekor, trillian, ctlog, tsa"
          - "Monitoring: Enabled for all components"
          
    - name: "Record deployment info"
      set_fact:
        deployment_timestamp: "{{ ansible_date_time.iso8601 }}"
        deployment_user: "{{ ansible_user_id }}"

  tasks:
    - name: "Step 1: Install required operators"
      include_role:
        name: install-operators
      tags: ["operators", "setup"]
        
    - name: "Step 2: Setup baseline namespace"
      include_role:
        name: setup-baseline-namespace
      tags: ["namespace", "setup"]

    - name: "Step 3: Deploy baseline TAS instance"
      include_role:
        name: deploy-baseline-tas
      tags: ["tas", "deploy"]

    - name: "Step 4: Deploy monitoring stack"
      include_role:
        name: deploy-monitoring
      when: monitoring.enabled | default(true)
      tags: ["monitoring", "deploy"]