# Main Baseline Infrastructure Playbook
---
- name: "Deploy TAS Baseline Infrastructure"
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    baseline_namespace: "{{ baseline.namespace }}"
    
  pre_tasks:
    - name: "Display deployment overview"
      debug:
        msg:
          - "================================================================"
          - "          TAS Baseline Infrastructure Deployment"
          - "================================================================"
          - " Target Namespace: {{ baseline_namespace }}"
          
    - name: "Record deployment info"
      set_fact:
        deployment_timestamp: "{{ ansible_date_time.iso8601 }}"
        deployment_user: "{{ ansible_user_id }}"

  tasks:
    - name: "Install required operators"
      include_role:
        name: install-operators
      tags: ["operators", "setup"]
        
    - name: "Deploy keycloak resources"
      include_role:
        name: deploy-keycloak-resources
      tags: ["keycloak", "deploy"]

    - name: "Setup baseline namespace"
      include_role:
        name: setup-baseline-namespace
      tags: ["namespace", "setup"]

    - name: "Deploy baseline TAS instance"
      include_role:
        name: deploy-baseline-tas
      tags: ["tas", "deploy"]

    - name: "Deploy monitoring stack"
      include_role:
        name: deploy-monitoring
      when: monitoring.enabled | default(true)
      tags: ["monitoring", "deploy"]